from decimal import Decimal
K = 5 #debe ser divisor de 100
FPS = 60

BLOCK_TIMER_MAX = 5 * FPS / K
CAPACITY_MAX = 3
#TIMESTEP = Decimal(0.01).__round__(2)
TIMESTEP = 1

STEP = K * Decimal(0.01).__round__(2)

SCREEN_WIDTH = 800
SCREEN_HEIGTH = 800

LIFT_WIDTH = 50
LIFT_HEIGHT = 50

POS_LIFT_INIT_Y = SCREEN_HEIGTH-LIFT_HEIGHT
POS_LIFT_INIT_X = int(SCREEN_WIDTH/2)  - int(LIFT_WIDTH/2)

FLOOR_WIDTH = 60
FLOOR_HEIGHT = 60

POS_FLOOR_INIT_Y = SCREEN_HEIGTH-FLOOR_HEIGHT
POS_FLOOR_INIT_X = int(SCREEN_WIDTH/2)  - int(FLOOR_WIDTH/2)

FLOOR_COLOR = "Blue"
FLOOR_COLOR_PRESSED_LEFT = "Green"
FLOOR_COLOR_PRESSED_RIGHT = "Yellow"

END = 10
T1 = FPS * 2
T2 = FPS * 4

T_EVENT_PERSON_SEG = 20
T_EVENT_PERSON_MS = T_EVENT_PERSON_SEG * 1000
T_EVENT_PERSON = int(T_EVENT_PERSON_MS/ K)

MAX_TOTALS = 10000