from decimal import Decimal

BLOCK_TIMER_MAX = 100
CAPACITY_MAX = 3
#TIMESTEP = Decimal(0.01).__round__(2)
TIMESTEP = 1
FPS = 60
STEP = Decimal(0.02).__round__(2)

SCREEN_WIDTH = 800
SCREEN_HEIGTH = 1000

LIFT_WIDTH = 50
LIFT_HEIGHT = 50

POS_LIFT_INIT_Y = SCREEN_HEIGTH-LIFT_HEIGHT
POS_LIFT_INIT_X = int(SCREEN_WIDTH/2)  - int(LIFT_WIDTH/2)

FLOOR_WIDTH = 60
FLOOR_HEIGHT = 60

POS_FLOOR_INIT_Y = SCREEN_HEIGTH-FLOOR_HEIGHT
POS_FLOOR_INIT_X = int(SCREEN_WIDTH/2)  - int(FLOOR_WIDTH/2)

FLOOR_COLOR = "Blue"
FLOOR_COLOR_PRESSED = "Green"

END = 10
T1 = FPS * 2
T2 = 300